// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: pkg/common/operations.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_OPEN     OperationType = 0
	OperationType_CLOSE    OperationType = 1
	OperationType_READ     OperationType = 2
	OperationType_APPEND   OperationType = 3
	OperationType_DELETE   OperationType = 4
	OperationType_SNAPSHOT OperationType = 5
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPEN",
		1: "CLOSE",
		2: "READ",
		3: "APPEND",
		4: "DELETE",
		5: "SNAPSHOT",
	}
	OperationType_value = map[string]int32{
		"OPEN":     0,
		"CLOSE":    1,
		"READ":     2,
		"APPEND":   3,
		"DELETE":   4,
		"SNAPSHOT": 5,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_common_operations_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_pkg_common_operations_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_common_operations_proto_rawDescGZIP(), []int{0}
}

var File_pkg_common_operations_proto protoreflect.FileDescriptor

var file_pkg_common_operations_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x54, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x52,
	0x45, 0x41, 0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x50, 0x50, 0x45, 0x4e, 0x44, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x04, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x4e, 0x41, 0x50, 0x53, 0x48, 0x4f, 0x54, 0x10, 0x05, 0x42, 0x26, 0x5a, 0x24, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x66, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_common_operations_proto_rawDescOnce sync.Once
	file_pkg_common_operations_proto_rawDescData = file_pkg_common_operations_proto_rawDesc
)

func file_pkg_common_operations_proto_rawDescGZIP() []byte {
	file_pkg_common_operations_proto_rawDescOnce.Do(func() {
		file_pkg_common_operations_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_common_operations_proto_rawDescData)
	})
	return file_pkg_common_operations_proto_rawDescData
}

var file_pkg_common_operations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_common_operations_proto_goTypes = []interface{}{
	(OperationType)(0), // 0: common.OperationType
}
var file_pkg_common_operations_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_common_operations_proto_init() }
func file_pkg_common_operations_proto_init() {
	if File_pkg_common_operations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_common_operations_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_common_operations_proto_goTypes,
		DependencyIndexes: file_pkg_common_operations_proto_depIdxs,
		EnumInfos:         file_pkg_common_operations_proto_enumTypes,
	}.Build()
	File_pkg_common_operations_proto = out.File
	file_pkg_common_operations_proto_rawDesc = nil
	file_pkg_common_operations_proto_goTypes = nil
	file_pkg_common_operations_proto_depIdxs = nil
}
