// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: pkg/common/permissions.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionGroup int32

const (
	PermissionGroup_NONE             PermissionGroup = 0
	PermissionGroup_Application      PermissionGroup = 1
	PermissionGroup_ApplicationGroup PermissionGroup = 2
	PermissionGroup_All              PermissionGroup = 4
)

// Enum value maps for PermissionGroup.
var (
	PermissionGroup_name = map[int32]string{
		0: "NONE",
		1: "Application",
		2: "ApplicationGroup",
		4: "All",
	}
	PermissionGroup_value = map[string]int32{
		"NONE":             0,
		"Application":      1,
		"ApplicationGroup": 2,
		"All":              4,
	}
)

func (x PermissionGroup) Enum() *PermissionGroup {
	p := new(PermissionGroup)
	*p = x
	return p
}

func (x PermissionGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_common_permissions_proto_enumTypes[0].Descriptor()
}

func (PermissionGroup) Type() protoreflect.EnumType {
	return &file_pkg_common_permissions_proto_enumTypes[0]
}

func (x PermissionGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionGroup.Descriptor instead.
func (PermissionGroup) EnumDescriptor() ([]byte, []int) {
	return file_pkg_common_permissions_proto_rawDescGZIP(), []int{0}
}

type PermissionType int32

const (
	PermissionType_NONE0  PermissionType = 0
	PermissionType_Read   PermissionType = 1
	PermissionType_Write  PermissionType = 2
	PermissionType_Delete PermissionType = 4
)

// Enum value maps for PermissionType.
var (
	PermissionType_name = map[int32]string{
		0: "NONE0",
		1: "Read",
		2: "Write",
		4: "Delete",
	}
	PermissionType_value = map[string]int32{
		"NONE0":  0,
		"Read":   1,
		"Write":  2,
		"Delete": 4,
	}
)

func (x PermissionType) Enum() *PermissionType {
	p := new(PermissionType)
	*p = x
	return p
}

func (x PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_common_permissions_proto_enumTypes[1].Descriptor()
}

func (PermissionType) Type() protoreflect.EnumType {
	return &file_pkg_common_permissions_proto_enumTypes[1]
}

func (x PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionType.Descriptor instead.
func (PermissionType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_common_permissions_proto_rawDescGZIP(), []int{1}
}

var File_pkg_common_permissions_proto protoreflect.FileDescriptor

var file_pkg_common_permissions_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x4b, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x6c,
	0x6c, 0x10, 0x04, 0x2a, 0x3c, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x4f, 0x4e, 0x45, 0x30, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10,
	0x04, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x66, 0x73, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_common_permissions_proto_rawDescOnce sync.Once
	file_pkg_common_permissions_proto_rawDescData = file_pkg_common_permissions_proto_rawDesc
)

func file_pkg_common_permissions_proto_rawDescGZIP() []byte {
	file_pkg_common_permissions_proto_rawDescOnce.Do(func() {
		file_pkg_common_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_common_permissions_proto_rawDescData)
	})
	return file_pkg_common_permissions_proto_rawDescData
}

var file_pkg_common_permissions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_common_permissions_proto_goTypes = []interface{}{
	(PermissionGroup)(0), // 0: common.PermissionGroup
	(PermissionType)(0),  // 1: common.PermissionType
}
var file_pkg_common_permissions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_common_permissions_proto_init() }
func file_pkg_common_permissions_proto_init() {
	if File_pkg_common_permissions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_common_permissions_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_common_permissions_proto_goTypes,
		DependencyIndexes: file_pkg_common_permissions_proto_depIdxs,
		EnumInfos:         file_pkg_common_permissions_proto_enumTypes,
	}.Build()
	File_pkg_common_permissions_proto = out.File
	file_pkg_common_permissions_proto_rawDesc = nil
	file_pkg_common_permissions_proto_goTypes = nil
	file_pkg_common_permissions_proto_depIdxs = nil
}
