// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: internal/chunkserver/chunkserver.proto

package chunkserver

import (
	common "github.com/distributed-fs/pkg/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileIORequest is a request to make file io operation
type FileIORequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationId string               `protobuf:"bytes,1,opt,name=ApplicationId,proto3" json:"ApplicationId,omitempty"`
	Token         string               `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Operation     common.OperationType `protobuf:"varint,3,opt,name=Operation,proto3,enum=common.OperationType" json:"Operation,omitempty"`
	Filename      string               `protobuf:"bytes,4,opt,name=Filename,proto3" json:"Filename,omitempty"`
	Bytes         int32                `protobuf:"varint,5,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Offset        int32                `protobuf:"varint,6,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Data          []byte               `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *FileIORequest) Reset() {
	*x = FileIORequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_chunkserver_chunkserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileIORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileIORequest) ProtoMessage() {}

func (x *FileIORequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chunkserver_chunkserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileIORequest.ProtoReflect.Descriptor instead.
func (*FileIORequest) Descriptor() ([]byte, []int) {
	return file_internal_chunkserver_chunkserver_proto_rawDescGZIP(), []int{0}
}

func (x *FileIORequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *FileIORequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FileIORequest) GetOperation() common.OperationType {
	if x != nil {
		return x.Operation
	}
	return common.OperationType_OPEN
}

func (x *FileIORequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileIORequest) GetBytes() int32 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *FileIORequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileIORequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// FileIOResponse is a response from a chunkserver when a request is made for a file operation
type FileIOResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *FileIOResponse) Reset() {
	*x = FileIOResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_chunkserver_chunkserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileIOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileIOResponse) ProtoMessage() {}

func (x *FileIOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_chunkserver_chunkserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileIOResponse.ProtoReflect.Descriptor instead.
func (*FileIOResponse) Descriptor() ([]byte, []int) {
	return file_internal_chunkserver_chunkserver_proto_rawDescGZIP(), []int{1}
}

func (x *FileIOResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileIOResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_chunkserver_chunkserver_proto protoreflect.FileDescriptor

var file_internal_chunkserver_chunkserver_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x4f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x33, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x4f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x32, 0x62, 0x0a, 0x0b, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x53, 0x0a, 0x16, 0x53, 0x65, 0x72, 0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49,
	0x4f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x4f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x64, 0x2d, 0x66, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_chunkserver_chunkserver_proto_rawDescOnce sync.Once
	file_internal_chunkserver_chunkserver_proto_rawDescData = file_internal_chunkserver_chunkserver_proto_rawDesc
)

func file_internal_chunkserver_chunkserver_proto_rawDescGZIP() []byte {
	file_internal_chunkserver_chunkserver_proto_rawDescOnce.Do(func() {
		file_internal_chunkserver_chunkserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_chunkserver_chunkserver_proto_rawDescData)
	})
	return file_internal_chunkserver_chunkserver_proto_rawDescData
}

var file_internal_chunkserver_chunkserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_chunkserver_chunkserver_proto_goTypes = []interface{}{
	(*FileIORequest)(nil),     // 0: chunkserver.FileIORequest
	(*FileIOResponse)(nil),    // 1: chunkserver.FileIOResponse
	(common.OperationType)(0), // 2: common.OperationType
}
var file_internal_chunkserver_chunkserver_proto_depIdxs = []int32{
	2, // 0: chunkserver.FileIORequest.Operation:type_name -> common.OperationType
	0, // 1: chunkserver.Chunkserver.ServeClientFileRequest:input_type -> chunkserver.FileIORequest
	1, // 2: chunkserver.Chunkserver.ServeClientFileRequest:output_type -> chunkserver.FileIOResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_chunkserver_chunkserver_proto_init() }
func file_internal_chunkserver_chunkserver_proto_init() {
	if File_internal_chunkserver_chunkserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_chunkserver_chunkserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileIORequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_chunkserver_chunkserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileIOResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_chunkserver_chunkserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_chunkserver_chunkserver_proto_goTypes,
		DependencyIndexes: file_internal_chunkserver_chunkserver_proto_depIdxs,
		MessageInfos:      file_internal_chunkserver_chunkserver_proto_msgTypes,
	}.Build()
	File_internal_chunkserver_chunkserver_proto = out.File
	file_internal_chunkserver_chunkserver_proto_rawDesc = nil
	file_internal_chunkserver_chunkserver_proto_goTypes = nil
	file_internal_chunkserver_chunkserver_proto_depIdxs = nil
}
